table:
  name: file
  schema: public
event_triggers:
  - name: create_file_thumbnail
    definition:
      enable_manual: false
      insert:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: http://host.docker.internal:3000/api/create-thumbnail
    request_transform:
      body:
        action: transform
        template: |-
          {
            "fileId": {{$body.event.data.new.id}}
          }
      template_engine: Kriti
      version: 2
    cleanup_config:
      batch_size: 10000
      clean_invocation_logs: false
      clear_older_than: 168
      paused: true
      schedule: 0 0 * * *
      timeout: 60
